#if !canImport(ObjectiveC)
import XCTest

extension QueryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__QueryTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(QueryTests.__allTests__QueryTests),
    ]
}
#endif
