#if !canImport(ObjectiveC)
import XCTest

extension FormParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FormParserTests = [
        ("testKeyValuePair", testKeyValuePair),
    ]
}

extension TokenizerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TokenizerTests = [
        ("testSubstringHash", testSubstringHash),
        ("testTokenizer", testTokenizer),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FormParserTests.__allTests__FormParserTests),
        testCase(TokenizerTests.__allTests__TokenizerTests),
    ]
}
#endif
